### ISSUE TITLE
Cannot get the same oracle result on Pubmed_trunc dataset

### ISSUE THREAD

**Issue by hustcxx** [nianlonggu/MemSum#10]
oracle result of pubmed_trunc in your paper is   45.12/20.33/40.19. but I download the dataset you provided , 
but I  got oracle result:
1 ROUGE-1 Average_R: 0.31187 (95%-conf.int. 0.30779 - 0.31588)
1 ROUGE-1 Average_P: 0.56634 (95%-conf.int. 0.56157 - 0.57099)
1 ROUGE-1 Average_F: 0.37910 (95%-conf.int. 0.37539 - 0.38300)
---------------------------------------------
1 ROUGE-2 Average_R: 0.13605 (95%-conf.int. 0.13329 - 0.13893)
1 ROUGE-2 Average_P: 0.25674 (95%-conf.int. 0.25167 - 0.26153)
1 ROUGE-2 Average_F: 0.16707 (95%-conf.int. 0.16387 - 0.17027)
---------------------------------------------
1 ROUGE-L Average_R: 0.27617 (95%-conf.int. 0.27245 - 0.27985)
1 ROUGE-L Average_P: 0.50572 (95%-conf.int. 0.50079 - 0.51033)
1 ROUGE-L Average_F: 0.33679 (95%-conf.int. 0.33319 - 0.34051)

I would appreciate it if you could provide the calculation code.Thanks.

**Comment by nianlonggu** [comment]
@hustcxx 
Hi, check this code:
https://github.com/nianlonggu/MemSum/blob/main/oracle_score_compute.ipynb

Your precision looks high. Did you set a small number to max_num_extracted_sentences? It can be set to None

**Comment by hustcxx** [comment]
It seems really weird, I used your code, and set max_num_extracted_sentences= 7, but got the result:
{'rouge1': AggregateScore(low=Score(precision=0.5331010262740428, recall=0.44525792991904944, fmeasure=0.472935454736468), mid=Score(precision=0.536385247921467, recall=0.44900115450155387, fmeasure=0.47574359864201643), high=Score(precision=0.5399545746454774, recall=0.4526085346313322, fmeasure=0.4783337137580275)), 'rouge2': AggregateScore(low=Score(precision=0.22993582754897907, recall=0.18510506224558343, fmeasure=0.19874288797317347), mid=Score(precision=0.23395676021137798, recall=0.188100224082128, fmeasure=0.20181358965695168), high=Score(precision=0.23825844021628662, recall=0.19113032477633574, fmeasure=0.20490523001431124)), 'rougeLsum': AggregateScore(low=Score(precision=0.4739550638016725, recall=0.39320809978058563, fmeasure=0.4186185085765082), mid=Score(precision=0.47769312951010967, recall=0.3963812010516099, fmeasure=0.4215347799958107), high=Score(precision=0.48118495480321133, recall=0.39916286053105826, fmeasure=0.42403697923095535))}

it is still different from the paper report result: 45.12/20.33/40.19.

**Comment by nianlonggu** [comment]
@hustcxx 
1) set max_num_extracted_sentences = None , or don’t set it. This is what I did in the previous code I shared. The greedy method will decide when to stop based on if rouge keep increases or not.

2) RougeAggregator did bootstrapping sampling, so therer is randomness coming from the aggregator, not from the greedy extract function. Everytime you will see a slightly different score. The score you produced is close enough to the score presented in the paper, at least much higher than your first version.

**Comment by hustcxx** [comment]
@nianlonggu

**Comment by hustcxx** [comment]
@nianlonggu 
OK.  the last question, rouge_score result include low/mid/high, the final result is the average of them?

**Comment by nianlonggu** [comment]
> @nianlonggu OK. the last question, rouge_score result include low/mid/high, the final result is the average of them?

Hi, I would use the mid value as the final results, because low / high represents the lower and upper bound for the 95% confidence level. 
Alternatively, you can also simply average the F1 scores for each test sample, then you may get a score that is close to the mid value produced by Aggregator.

Hope this helps.

**Comment by hustcxx** [comment]
@nianlonggu 
Thanks for your patience and your reply really helped me a lot.

**Comment by nianlonggu** [comment]
> @nianlonggu Thanks for your patience and your reply really helped me a lot.

You are welcome :D
