### ISSUE TITLE
Pre-trained/fine-tuned model available for inference?

### ISSUE THREAD

**Issue by yungsinatra0** [nianlonggu/MemSum#13]
Hello! I'd like to give MemSum a try, however I don't have access to machine that I can use for training yet. By any chance, are there any checkpoints that I can use for inference? Thank you!

**Comment by nianlonggu** [comment]
Hi, the pretrained checkpoints are stored at huggingface hub, and you can load them by following the descriptions in README (I just made some updates to make them more clear.)
You can train the model using google colab: https://colab.research.google.com/github/nianlonggu/MemSum/blob/main/Training_Pipeline.ipynb

**Comment by yungsinatra0** [comment]
@nianlonggu Thank you very much! I saw the updated description in README and already have managed to use the model :) Quick note though, I believe the Colab link is not working 

```
Could not find Training_Pipeline.ipynb in https://api.github.com/repos/nianlonggu/MemSum/contents/?per_page=100&ref=main
ub@https://ssl.gstatic.com/colaboratory-static/common/f07f7aa1a34f27b18107e35c731a3209/external_polymer_binary.js:88:517
gJ@https://ssl.gstatic.com/colaboratory-static/common/f07f7aa1a34f27b18107e35c731a3209/external_polymer_binary.js:2236:68
iHa/<@https://ssl.gstatic.com/colaboratory-static/common/f07f7aa1a34f27b18107e35c731a3209/external_polymer_binary.js:2223:442
wa@https://ssl.gstatic.com/colaboratory-static/common/f07f7aa1a34f27b18107e35c731a3209/external_polymer_binary.js:21:57
sa.prototype.next_@https://ssl.gstatic.com/colaboratory-static/common/f07f7aa1a34f27b18107e35c731a3209/external_polymer_binary.js:19:195
laa/this.next@https://ssl.gstatic.com/colaboratory-static/common/f07f7aa1a34f27b18107e35c731a3209/external_polymer_binary.js:22:48
b@https://ssl.gstatic.com/colaboratory-static/common/f07f7aa1a34f27b18107e35c731a3209/external_polymer_binary.js:22:309
```

**Comment by nianlonggu** [comment]
Thanks for pointing that out :) Now this link is accessible.

**Comment by yungsinatra0** [comment]
Yep, can confirm it's working now!
