### ISSUE TITLE
Clarification on the oracle/sampled summaries

### ISSUE THREAD

**Issue by vikigenius** [nianlonggu/MemSum#2]
Looking at the paper and data is not very clear how you have obtained the oracle summaries.

In the paper you say that B=2 and at each step you sample 1 greedy selection and 1 sub optimal selection. But that means the number of summaries should be a power of 2? But I see that's not the case?

I would appreciate it if you could clarify this selection process or provide some code?

**Comment by nianlonggu** [comment]
Thanks for asking. 
When setting B=2, after getting a list of sub-optimal candidate sentences, we perform pruning by only keeping the top B sentence and moving on, this is similar to the idea in beam search.
I have updated the code for the greedy extract part. Have a check 
https://github.com/nianlonggu/MemSum#addition-info-code-for-obtaining-the-greedy-summary-of-a-document-and-creating-high-rouge-episodes-for-training-the-model
