### ISSUE TITLE
Missing `summarizers.py` and `download_and_load_word_embedding.py`

### ISSUE THREAD

**Issue by TongLi3701** [nianlonggu/MemSum#3]
Hi @nianlonggu ,

Thanks for providing the code.

I wanted to try your method but found some files are missing.

For example, based on your README file, it should be a file called `summarizers.py` but I could not find it.

In addition, is there a file called `download_and_load_word_embedding.py`? I am not able to find it as well.

I really appreciate any help you can provide.

**Comment by nianlonggu** [comment]
Hi @TongLi3701 ,

Thanks for the feedback! I noticed that the file summarizers.py was missing. I have just uploaded it. Now it should be fine to run the code.

The file download_and_load_word_embedding.py is used in the previous branch.
In the most updated "main" branch, this file is no longer needed, and you can download all data and models from google drive, as shown in the README.

Let me know if there is any question. Thanks.

**Comment by TongLi3701** [comment]
Thanks a lot for your quick reply.
