### ISSUE TITLE
Clarification of the data format

### ISSUE THREAD

**Issue by TongLi3701** [nianlonggu/MemSum#4]
Hi @nianlonggu ,

Thanks a lot for your previous reply.

I just have some questions regarding your data format for PubMed.

For example, for `train_PUBMED.jsonl`, the keys are `['text', 'summary', 'indices', 'score']`, but for the others like `test_PUBMED.jsonl`,  we only have `['summary', 'text', 'sorted_indices']`.

What are these keys mean?  for example, `sorted_indices` and `indices` and `score`?

Also I can see `test_PUBMED_ORACLE.jsonl`, what is the difference between it and `test_PUBMED.jsonl`.

How did you generate these files?

If I understand correctly, during your training, you need to extract the gold extractive summaries and then during validation and test, your scores are reported by comparing with the real summaries.

Sorry for so many questions.

Thanks in advance.

**Comment by nianlonggu** [comment]
> Hi @nianlonggu ,
> 
> Thanks a lot for your previous reply.
> 
> I just have some questions regarding your data format for PubMed.
> 
> For example, for `train_PUBMED.jsonl`, the keys are `['text', 'summary', 'indices', 'score']`, but for the others like `test_PUBMED.jsonl`, we only have `['summary', 'text', 'sorted_indices']`.
> 
> What are these keys mean? for example, `sorted_indices` and `indices` and `score`?
> 
> Also I can see `test_PUBMED_ORACLE.jsonl`, what is the difference between it and `test_PUBMED.jsonl`.
> 
> How did you generate these files?
> 
> If I understand correctly, during your training, you need to extract the gold extractive summaries and then during validation and test, your scores are reported by comparing with the real summaries.
> 
> Sorry for so many questions.
> 
> Thanks in advance.

hi @TongLi3701 ,


text means the document to summarize, summary means the ground truth summary (the abstract). indices means a list of high-Rouge episodes, each representing a way to summarize the document. Please see section 3.4 and appendix E in the paper.   score is a list of mean rouge F scores for each episode.


sorted indices was not used in the test file. I created it for debugging. I can remove it in the future.

test_pubmed and test_pubmed_oracle are basically identical. Except that in test_pubmed_oracle I used the greedy algorithm introduced in the paper to extract an oracle summary for each document. This is used to compute Oracle score in the results section.

your last understanding was right. That is what I did, as shown in the code snippet in this README

**Comment by TongLi3701** [comment]
Thanks for your quick reply @nianlonggu.

It definitely helps a lot!

**Comment by tm1412** [comment]
So, is it correct that we only need the 'summary' and 'text' fields in the test and validation files to proceed with training and testing?

**Comment by nianlonggu** [comment]
> 

Yes: https://github.com/nianlonggu/MemSum/blob/50a507b0d24ad49fc0e8bca78903858a7c9ca2b8/src/MemSum_Full/datautils.py#L127
