### ISSUE TITLE
can not find the EHE in model.py module 

### ISSUE THREAD

**Issue by xxz-wow** [nianlonggu/MemSum#5]
does ExtractionContextDecoder actually mean ExtractionContextEncoder？

**Comment by nianlonggu** [comment]
@xxz-wow Yes correct.  The EHE was once called a decoder when developing the model. Later on it was named EHE but the old name was kept in the code.

**Comment by xxz-wow** [comment]
ok ，thank you

**Comment by xxz-wow** [comment]
do you have the ppt of this paper? l want to introduce this paper to my group

**Comment by nianlonggu** [comment]
> do you have the ppt of this paper? l want to introduce this paper to my group

Here it is:

https://github.com/nianlonggu/MemSum/blob/main/slides_for_paper.pdf

**Comment by xxz-wow** [comment]
> > do you have the ppt of this paper? l want to introduce this paper to my group
> 
> Here it is:
> 
> https://github.com/nianlonggu/MemSum/blob/main/slides_for_paper.pdf

thank you very much!

**Comment by nianlonggu** [comment]
> > > do you have the ppt of this paper? l want to introduce this paper to my group
> > 
> > 
> > Here it is:
> > https://github.com/nianlonggu/MemSum/blob/main/slides_for_paper.pdf
> 
> thank you very much!

You are welcome.

We have also created a jupyter notebook on google colab for processing custom data and train / test the model.
https://colab.research.google.com/github/nianlonggu/MemSum/blob/main/Data_processing_training_and_testing_for_MemSum.ipynb
You may find it useful for a live demo.

Best,
