### ISSUE TITLE
Can u instruction for custom data

### ISSUE THREAD

**Issue by batman-do** [nianlonggu/MemSum#6]
- Hey guys, can u share to instruction for custom data from preprocessing data -> train -> inference
 Thanks guys !

**Comment by nianlonggu** [comment]
> * Hey guys, can u share to instruction for custom data from preprocessing data -> train -> inference
>   Thanks guys !

Hi,

The instruction on processing custom data and training the model is available on the jupyter notebook (you can directly run it on colab):

https://github.com/nianlonggu/MemSum/blob/main/Data_processing_training_and_testing_for_MemSum.ipynb

Check the README for detailed info.

**Comment by batman-do** [comment]
> > * Hey guys, can u share to instruction for custom data from preprocessing data -> train -> inference
> >   Thanks guys !
> 
> Hi,
> 
> The instruction on processing custom data and training the model is available on the jupyter notebook (you can directly run it on colab):
> 
> https://github.com/nianlonggu/MemSum/blob/main/Data_processing_training_and_testing_for_MemSum.ipynb
> 
> Check the README for detailed info.

Thanks u
