### ISSUE TITLE
When predict a custom dataset

### ISSUE THREAD

**Issue by batman-do** [nianlonggu/MemSum#7]
Hey guys @nianlonggu ,  I want to show rouge1/2/L score a summary from a docs !

I guess `sentence_score_history` in file `summarizers.py` in model MemSum , I guess right ?

Thanks guys

**Comment by nianlonggu** [comment]
> Hey guys @nianlonggu , I want to show rouge1/2/L score a summary from a docs !
> 
> I guess `sentence_score_history` in file `summarizers.py` in model MemSum , I guess right ?
> 
> Thanks guys

Hi, did you mean to show how sentence scores change during the summarization process?
If so, then yes, sentence_score_history is the variable that contains the history scores.

**Comment by batman-do** [comment]
> > Hey guys @nianlonggu , I want to show rouge1/2/L score a summary from a docs !
> > I guess `sentence_score_history` in file `summarizers.py` in model MemSum , I guess right ?
> > Thanks guys
> 
> Hi, did you mean to show how sentence scores change during the summarization process? If so, then yes, sentence_score_history is the variable that contains the history scores.

It show list array , each array.max()/array.sum() is score a sentence in summary , right ?

**Comment by nianlonggu** [comment]
> 

Yes, you can verify this by checking the shape or length of the array

**Comment by batman-do** [comment]
> > 
> 
> Yes, you can verify this by checking the shape or length of the array

Thanks guys
