### ISSUE TITLE
Do we need to provide ground truth summary to run greedy_summary?

### ISSUE THREAD

**Issue by asrlhhh** [nianlonggu/MemSum#8]
Hi, I am implementing a use case where an algorithm can sequentially generate the sentence that is most relevant to the summary of the text. It's pretty much similar to what the greedy_summary is designed for. 

However, when I am looking through your code implementation of greedy_summary (I haven't had time to look at paper yet), I noticed that it needs ground truth summary as input to pick the next most important sentence. I am thinking what if I use memsum to generate summary of a text first and feed that output as the parameter for greedy_summary, would that generate decent result?

**Comment by nianlonggu** [comment]
> 

Hi, greedy_summary requires the ground-truth summary, because its purpose is to get a subset of sentences from the document that is highly similar to the gold summary, which is then used to train MemSum. 
Do you mean to use MemSum extracted summary as the gold summary and then use greedy function to extract a list of sentences? This sounds like reversing the role between greedy and memsum. The challenge is how to train MemSum on your dataset when there is no ground-truth summary.

**Comment by asrlhhh** [comment]
Hi Nianlong, thanks for responding. My primary purpose is not to use MemSum extracted summary as the gold summary, but to implement function like below:

def extract_summary(text, num_of_sentences)

Where the **num_of_sentences** indicate the exact number of sentences to extract for summarization. When the value of **num_of_sentences** increase, the algorithm should gradually pick the most relevant sentence from the remaining text and add it to the summary. For example, when **num_of_sentences** is set to 1, it will give exactly the most important sentence out of the text for summary, and when it's set to 2, it will give the most important and second to most important sentences out of the text for summary. This seems exactly like what the greedy_summary is doing, except it is using ground truth. 

But since it's part of the training scheme, I guess in runtime the model is still somehow replicate the same behavior? I noticed that the inference function has param max_extracted_sentences. But it's kinda weak enforcement. When I assign it to 7, it sometimes give me 6 or 5 sentences. I wish there is way to to let it give me the exact number of sentences as indicated.

**Comment by nianlonggu** [comment]
> Hi Nianlong, thanks for responding. My primary purpose is not to use MemSum extracted summary as the gold summary, but to implement function like below:
> 
> def extract_summary(text, num_of_sentences)
> 
> Where the **num_of_sentences** indicate the exact number of sentences to extract for summarization. When the value of **num_of_sentences** increase, the algorithm should gradually pick the most relevant sentence from the remaining text and add it to the summary. For example, when **num_of_sentences** is set to 1, it will give exactly the most important sentence out of the text for summary, and when it's set to 2, it will give the most important and second to most important sentences out of the text for summary. This seems exactly like what the greedy_summary is doing, except it is using ground truth.
> 
> But since it's part of the training scheme, I guess in runtime the model is still somehow replicate the same behavior? I noticed that the inference function has param max_extracted_sentences. But it's kinda weak enforcement. When I assign it to 7, it sometimes give me 6 or 5 sentences. I wish there is way to to let it give me the exact number of sentences as indicated.

Hi, what you described is exactly what MemSum wants to achieve. If you want to have a more strict control over number of sentences to be extracted, simply set  p_stop_thres = 1.0 when call  memsum.extract() function

**Comment by asrlhhh** [comment]
Ohh perfect! I will try it out. Sorry I should have spent some time reading through the paper
